"""add analysis report and news chunk tables

Revision ID: 00244c8ac0aa
Revises: f79f36f4bc5b
Create Date: 2026-01-21 22:59:48.438081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00244c8ac0aa'
down_revision: Union[str, Sequence[str], None] = 'f79f36f4bc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
