"""Add esg_analysis column

Revision ID: 131ce0d4a98e
Revises: 00244c8ac0aa
Create Date: 2026-01-22 13:50:26.015438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '131ce0d4a98e'
down_revision: Union[str, Sequence[str], None] = '00244c8ac0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('esg_analysis', sa.JSON(), nullable=True))
    op.drop_column('analysis_reports', 'esg_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('esg_score', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.drop_column('analysis_reports', 'esg_analysis')
    # ### end Alembic commands ###
