"""Add financial_analysis column

Revision ID: 3e07e0c81ffa
Revises: 131ce0d4a98e
Create Date: 2026-01-22 14:53:51.829164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e07e0c81ffa'
down_revision: Union[str, Sequence[str], None] = '131ce0d4a98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('financial_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_reports', 'financial_analysis')
    # ### end Alembic commands ###
