
import sys
import os
from unittest.mock import MagicMock, patch

# Add backend to path
sys.path.append(os.path.join(os.getcwd(), 'backend'))

from app.agents.state import AgentState
from app.agents.workflow import defense_phase
from app.agents.judge import judge_agent
from app.agents.citation_models import SourceMetadata

def test_debate_flow():
    print("Testing Debate Flow...")

    # Mock State
    state = {
        'company_name': 'TestCorp',
        'company_id': 'test-id',
        'analysis_persona': 'INVESTOR',
        'citation_registry': {},
        'news_analysis': "News says bad things [N1].",
        'financial_analysis': "Financials are good [F1].",
        'claims_analysis': "Docs are okay [D1].",
        'news_critique': "Financials ignore the scandal [N1].",
        'financial_critique': "News is sensationalist [F1].",
        'claims_critique': "Docs support financials [D1].",
        'government_arguments': ["Financials ignore the scandal [N1]."], # News critiquing Fin
        'opposition_arguments': ["News is sensationalist [F1]."], # Fin critiquing News
        'job_id': 'test-job'
    }

    # Mock LLM response for defense
    mock_llm_response = MagicMock()
    mock_llm_response.content = "Defensive argument with [F1]"
    
    # Mock LLM for Judge
    mock_judge_response = MagicMock()
    mock_judge_response.content = """
    {
        "decision": "HOLD",
        "confidence_score": 75,
        "confidence_reasoning": "Good data [F1]",
        "justification": "Mixed signals [N1] [F1]",
        "key_concerns": ["Scandal [N1]", "Growth [F1]"],
        "summary": "Summary here.",
        "bull_case": "Bull case.",
        "bear_case": "Bear case.",
        "risk_factors": "Risks.",
        "debate": {
            "government_summary": "Gov summary",
            "government_arguments": ["Gov arg 1"],
            "opposition_summary": "Opp summary",
            "opposition_arguments": ["Opp arg 1"],
            "verdict": "Verdict",
            "transcript": "**Transcript** generated by Judge"
        }
    }
    """

    with patch('app.agents.financial_agent.get_llm') as mock_get_llm_fin, \
         patch('app.agents.news_agent.get_llm') as mock_get_llm_news, \
         patch('app.agents.judge.get_llm') as mock_get_llm_judge:
        
        # Setup mocks
        mock_get_llm_fin.return_value.invoke.return_value = mock_llm_response
        mock_get_llm_news.return_value.invoke.return_value = mock_llm_response
        mock_get_llm_judge.return_value.invoke.return_value = MagicMock(content=mock_judge_response.content)

        # 1. Run Defense Phase
        print("\n--- Running Defense Phase ---")
        defense_update = defense_phase(state)
        print("Defense Update Keys:", defense_update.keys())
        
        # Update state mimicking workflow
        state.update(defense_update)
        state['government_arguments'] = defense_update['government_arguments']
        state['opposition_arguments'] = defense_update['opposition_arguments']

        print("Gov Args:", state['government_arguments'])
        print("Opp Args:", state['opposition_arguments'])

        # 2. Run Judge Agent
        print("\n--- Running Judge Agent ---")
        judge_result = judge_agent(state)
        print("Judge Result Keys:", judge_result.keys())
        
        final_output = judge_result.get('final_output_json')
        if final_output:
            print("\nDebate Report from Final Output:")
            # final_output is a dict here because it was dumped in judge_agent
            debate_report = final_output.get('debate_report', {})
            import json
            print(json.dumps(debate_report, indent=2))
            
            if debate_report.get('transcript'):
                print("\n✅ Transcript found!")
            else:
                print("\n❌ Transcript MISSING!")
        else:
            print("No final output generated.")

if __name__ == "__main__":
    test_debate_flow()
